### PR TITLE
Remove myget source from readme

### PR DESCRIPTION
**Pull request by vicancy**
Sounds unnecessary to expose MyGet feeds to end users

### CODE REVIEW

**Comment by davidfowl** [comment]
Why not just have both?

**Comment by vicancy** [comment]
MyGet ones in current CI flow, might not ready to publish, it triggers everytime dev branch has commits. feels no need to add it to Readme, it might be misleading. We can add it back when later we change it to a more officially publish workflow, for example, only tagged ones are published.

**Comment by davidfowl** [comment]
I don't agree. I think it's fine to have both there. Github is where developers come to see the source code and use bleeding edge things. No need to hide it from them.

**Comment by vicancy** [comment]
OK, sounds fair

**Pull request merged**
