### PR TITLE
apply AppendMessageTracingId to persistent mode

### PR DESCRIPTION
**Pull request by wanlwanl**

### CODE REVIEW

**Comment by Y-Sindo** [comment]
```
        protected override T AppendMessageTracingId<T>(T message)
        {
            if (_serviceManagerOptions.Value.EnableMessageTracing)
            {
                message.TracingId = MessageWithTracingIdHelper.Generate();
                return message;
            }

            return base.AppendMessageTracingId(message);
        }
```
Why don't you make `MessageWithTracingIdHelper.Generate()` an extension method?

**Comment by Y-Sindo** [comment]
And what is the difference between `Message.WithTracingId()` and `MessageWithTracingIdHelper.Generate()`

**Comment by wanlwanl** [comment]
> ```
>         protected override T AppendMessageTracingId<T>(T message)
>         {
>             if (_serviceManagerOptions.Value.EnableMessageTracing)
>             {
>                 message.TracingId = MessageWithTracingIdHelper.Generate();
>                 return message;
>             }
> 
>             return base.AppendMessageTracingId(message);
>         }
> ```
> 
> Why don't you make `MessageWithTracingIdHelper.Generate()` an extension method?

what do you mean? @Y-Sindo

**Comment by wanlwanl** [comment]
> And what is the difference between `Message.WithTracingId()` and `MessageWithTracingIdHelper.Generate()`

`WithTracingId` contains additional checks

**Comment by Y-Sindo** [comment]
```cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Threading;
using Microsoft.Azure.SignalR.Protocol;

namespace Microsoft.Azure.SignalR
{
    internal static class IMessageWithTracingIdExtensions
    {
        internal static ulong Prefix { get; set; } = (ulong)(Guid.NewGuid().GetHashCode() & 0x0FFF_FFFF) << 32;
        private static int _index = -1;

        // message tracing id is constructed in the format:
        // from most significant digit to least significant digit:
        // 8 hex digits: prefix of the server
        // 8 hex digits: message index
        // Usage:
        // - Messaging log category is enabled
        // - EnableMessageTracing is true for Management SDK


        public static T WithTracingId<T>(this T message) where T : IMessageWithTracingId
        {
            if (ServiceConnectionContainerScope.EnableMessageLog || ClientConnectionScope.IsDiagnosticClient)
            {
                message.WithTracingIdWithoutCheck();
            }
            return message;
        }

        public static T WithTracingIdWithoutCheck<T>(this T message) where T : IMessageWithTracingId
        {

                message.TracingId = Prefix + (uint)Interlocked.Increment(ref _index);

            return message;
        }
    }
}
```
Sth. like this.

**Comment by wanlwanl** [comment]
> > Why don't you make MessageWithTracingIdHelper.Generate() an extension method?
> 
> ```cs
> // Copyright (c) Microsoft. All rights reserved.
> // Licensed under the MIT license. See LICENSE file in the project root for full license information.
> 
> using System;
> using System.Threading;
> using Microsoft.Azure.SignalR.Protocol;
> 
> namespace Microsoft.Azure.SignalR
> {
>     internal static class IMessageWithTracingIdExtensions
>     {
>         internal static ulong Prefix { get; set; } = (ulong)(Guid.NewGuid().GetHashCode() & 0x0FFF_FFFF) << 32;
>         private static int _index = -1;
> 
>         // message tracing id is constructed in the format:
>         // from most significant digit to least significant digit:
>         // 8 hex digits: prefix of the server
>         // 8 hex digits: message index
>         // Usage:
>         // - Messaging log category is enabled
>         // - EnableMessageTracing is true for Management SDK
> 
> 
>         public static T WithTracingId<T>(this T message) where T : IMessageWithTracingId
>         {
>             if (ServiceConnectionContainerScope.EnableMessageLog || ClientConnectionScope.IsDiagnosticClient)
>             {
>                 message.WithTracingIdWithoutCheck();
>             }
>             return message;
>         }
> 
>         public static T WithTracingIdWithoutCheck<T>(this T message) where T : IMessageWithTracingId
>         {
> 
>                 message.TracingId = Prefix + (uint)Interlocked.Increment(ref _index);
> 
>             return message;
>         }
>     }
> }
> ```
> 
> Sth. like this.

Discussed offline, keep the original one is ok

**Review by vicancy — APPROVED** [review]

**Pull request merged**
